import { constructEvents, IEvent } from './event'

export type TShipControlsEventName =
  | 'SHIP_CONTROLS_FORWARD'
  | 'SHIP_CONTROLS_FORWARD_DOWN'
  | 'SHIP_CONTROLS_FORWARD_UP'
  | 'SHIP_CONTROLS_LEFT'
  | 'SHIP_CONTROLS_LEFT_DOWN'
  | 'SHIP_CONTROLS_LEFT_UP'
  | 'SHIP_CONTROLS_THRUST_LEFT'
  | 'SHIP_CONTROLS_THRUST_LEFT_UP'
  | 'SHIP_CONTROLS_RIGHT'
  | 'SHIP_CONTROLS_RIGHT_DOWN'
  | 'SHIP_CONTROLS_RIGHT_UP'
  | 'SHIP_CONTROLS_THRUST_RIGHT'
  | 'SHIP_CONTROLS_THRUST_RIGHT_UP'
  | 'SHIP_CONTROLS_FIRE'
  | 'SHIP_CONTROLS_FIRE_UP'
  | 'SHIP_CONTROLS_SPECIAL'
  | 'SHIP_CONTROLS_SPECIAL_UP'
  | 'SHIP_CONTROLS_DIVE'
  | 'SHIP_CONTROLS_DIVE_UP'

  // not active (yet?)
  | 'SHIP_CONTROLS_BACKWARDS'
  | 'SHIP_CONTROLS_BACKWARDS_DOWN'
  | 'SHIP_CONTROLS_BACKWARDS_UP'
  | 'SHIP_CONTROLS_THRUST_BACK'
  | 'SHIP_CONTROLS_THRUST_BACK_UP'
  | 'SHIP_CONTROLS_THRUST_FORWARD'
  | 'SHIP_CONTROLS_THRUST_FORWARD_UP'

export interface IShipControlsEvent extends IEvent {
  name: TShipControlsEventName
}

// note: re-typing the input `name` so that its fixed to TInputEventName
const _constructEvents: (
  events: Array<IShipControlsEvent['name'] | IShipControlsEvent>
) => Record<IShipControlsEvent['name'], IShipControlsEvent> = constructEvents as any

export const shipControlsEvents = _constructEvents([
  'SHIP_CONTROLS_FORWARD',
  'SHIP_CONTROLS_FORWARD_DOWN',
  'SHIP_CONTROLS_FORWARD_UP',
  'SHIP_CONTROLS_LEFT',
  'SHIP_CONTROLS_LEFT_DOWN',
  'SHIP_CONTROLS_LEFT_UP',
  'SHIP_CONTROLS_THRUST_LEFT',
  'SHIP_CONTROLS_THRUST_LEFT_UP',
  'SHIP_CONTROLS_RIGHT',
  'SHIP_CONTROLS_RIGHT_DOWN',
  'SHIP_CONTROLS_RIGHT_UP',
  'SHIP_CONTROLS_THRUST_RIGHT',
  'SHIP_CONTROLS_THRUST_RIGHT_UP',
  'SHIP_CONTROLS_FIRE',
  'SHIP_CONTROLS_FIRE_UP',
  'SHIP_CONTROLS_SPECIAL',
  'SHIP_CONTROLS_SPECIAL_UP',
  'SHIP_CONTROLS_DIVE',
  'SHIP_CONTROLS_DIVE_UP',
  'SHIP_CONTROLS_BACKWARDS',
  'SHIP_CONTROLS_BACKWARDS_DOWN',
  'SHIP_CONTROLS_BACKWARDS_UP',
  'SHIP_CONTROLS_THRUST_BACK',
  'SHIP_CONTROLS_THRUST_BACK_UP',
  'SHIP_CONTROLS_THRUST_FORWARD',
  'SHIP_CONTROLS_THRUST_FORWARD_UP',
])
